### ISSUE TITLE
Could not set uid on user[opendkim]

### ISSUE THREAD

**Issue by byblakout** [lvicainne/puppet-opendkim#11]
Trying your opendkim module, running into an issue on both Ubuntu 14.04 and 16.04
Forcing the GID/UID to 5010 is resulting in errors during the Puppet run.

```
Aug  9 19:16:56 ip-10-10-39-152 puppet-user[1666 (/Stage[main]/Opendkim::Install/Package[opendkim]/ensure) created
Aug  9 19:16:56 ip-10-10-39-152 puppet-user[1666]: (/Stage[main]/Opendkim::Config/Group[opendkim]/gid) gid changed '117' to '5010'
Aug  9 19:16:56 ip-10-10-39-152 puppet-user[1666]: Could not set uid on user[opendkim]: Execution of '/usr/sbin/usermod -u 5010 opendkim' returned 8: usermod: user opendkim is currently used by process 9310
Aug  9 19:16:56 ip-10-10-39-152 puppet-user[1666]: (/Stage[main]/Opendkim::Config/User[opendkim]/uid) change from 113 to 5010 failed: Could not set uid on user[opendkim]: Execution of '/usr/sbin/usermod -u 5010 opendkim' returned 8: usermod: user opendkim is currently used by process 9310
```

**Comment by byblakout** [comment]
Curious - why is it necessary?

**Comment by lvicainne** [comment]
Hi !
Your problem cal be easily solved if you stop opendkim during the 1st run of this module (thus, the system will be allowed to proceed to tha change of the UID/GID)/
For my usage, it is required to share the same UID/GID for files when they are share between several servers accros NFS.
I did a commit today in order to correct this behavioour for people who don't care GID and UID !
Feel free to submit some PR in order to improve this module ! :-)
Rgds

**Comment by byblakout** [comment]
Interesting - thanks for the incredibly fast response!
